### ISSUE TITLE
`bun@0.0.11` is incompatible with this module

### ISSUE THREAD

**Issue by Swivelgames** [naomik/bun#7]
Fifteen minutes before a demo, and out of no where I get this when deploying.

```
error bun@0.0.11: The engine "node" is incompatible with this module. Expected version "~0.10.12".
error Found incompatible module
```

We're talking about the `node` engine. Shouldn't this be `>=0.10.12`?!

**Comment by deoxxa** [comment]
You're deploying something you haven't tested fifteen minutes before a demo? This sounds like a "you" problem.

**Comment by Swivelgames** [comment]
@deoxxa I've been testing non-stop. But, upon pulling down the latest dependencies during the deploy, this has popped up out of no where.

**Comment by Swivelgames** [comment]
@deoxxa Instead of being rude, snarky, and inconsiderate, have you thought about why this is doesn't support newer versions of `node`, and possibly where to start with a resolution to this? I'm willing to contribute a PR if necessary.

**Comment by deoxxa** [comment]
Given that this project hasn't seen an update in three years, I'm guessing it's a change on your end. Maybe you're deploying with a different version of npm than you're testing with, or a different version of node. Not my pig, not my farm, not my problem.

The engines field _is_ clearly incorrect though, so feel free to submit a PR updating that and I'll push it to npm today.

**Comment by Swivelgames** [comment]
@deoxxa Thanks. There's an issue ticket on google's firebase utilities. They require their packages to be at the latest version in order to run, and their latest version just added this as a dependency, so we're seeing firebase start to fail across the board.

I'll see if the `mocha` tests will still run after the engine is updated. Otherwise they may be switching to `merge2` or another library.

**Comment by ShaharHD** [comment]
Started a new project like 30 min ago, copied a working package.json from an older project (couple of months old) - and same issue.

I'm getting the error due to ```"firebase-admin": "^5.2.1"```

Anything I can do to assist in resolving this?

**Comment by deoxxa** [comment]
Okay, I've published a new version with the engines field updated courtesy of @Swivelgames. Problem though: this is 0.0.12, which may not automatically be pulled in by `nodejs-firebase`: https://github.com/googleapis/nodejs-firestore/blob/5f38b0ab784bdf5d45a5edf9fa852cf34c48e822/package.json#L44.

Problem solved on this end though - time to go bug google to update their package.json too.
